### ISSUE TITLE
Is there a way to preview the changes before publishing

### ISSUE THREAD

**Issue by isbkch** [vsch/laravel-translation-manager#101]
It is hard to use the package in a production environment without preview. Is there a preview-like feature in this package ?

**Comment by vsch** [comment]
@isbkch, I am guessing you are referring to seeing the site as if the translations were published?

It can be easily added. The translation get routines already take flags to specify allways take the database translations (published or not) so it is a matter of storing a flag in the session or cookie to force always getting the database version for the session.

**Comment by vsch** [comment]
Added to working locales area https://github.com/vsch/laravel-translation-manager/wiki/Web-Interface#database-locales-and-working-set

Also available in the React UI under settings.
