### ISSUE TITLE
Bug with 2.4.32 version

### ISSUE THREAD

**Issue by Alorse** [vsch/laravel-translation-manager#102]
After update from 2.4.30 to 2.4.32, I get the next error:
```
> php artisan optimize

                                                                               
  [ErrorException]                                                             
  Declaration of App\Patches\TranslationManager\Manager::cacheTranslation($ke  
  y, $value, $locale) should be compatible with Vsch\TranslationManager\Manag  
  er::cacheTranslation($namespace, $group, $transKey, $value, $locale)
```

After this everything goes out of control, the solution is to return to version 2.4.30
2.4.32 version is the last one for laravel 5.4 truth?

**Comment by vsch** [comment]
@Alorse, you have some old cache files with conflicting declaration.

Try clearing with `php artisan clear-compiled` and maybe `cache:clear` or another cache clear commands. I am not sure which cache is causing the problem but it is a Laravel cached declaration issue.

**Comment by Alorse** [comment]
Yes, you're right, the was with update no updated files in "App\Patches\TranslationManager" folder, I had to update the files manually, is there another way or should this be automatic?

**Comment by Alorse** [comment]
Don't worry, it's was my problem, I had override the classes.
