### ISSUE TITLE
Error with PHP 7.2

### ISSUE THREAD

**Issue by schmidtflo** [vsch/laravel-translation-manager#113]
Using the translation manager throws an error when saving new translations:

`ErrorException: count(): Parameter must be an array or an object that implements Countable in file /home/.../vendor/vsch/laravel-translation-manager/src/Classes/TranslationFileRewriter.php on line 111`

As far as i could research it's an error because PHP 7.2 changed the count-function. https://github.com/php/php-src/blob/php-7.2.0RC4/UPGRADING (Line 226)

**Comment by vsch** [comment]
@schmidtflo, I have only used it with Php 7.0. I will have to install Php 7.2 and test it.

**Comment by vsch** [comment]
@schmidtflo, new version with the fix published. Yes it was the count() of non-array.

**Comment by schmidtflo** [comment]
Thanks, already successfully tested :+1:

**Comment by Octet83** [comment]
Not working for older version like 2.5 for Laravel LTS 5.5
