### ISSUE TITLE
Call to undefined function Vsch\TranslationManager\getSupportedLocale()

### ISSUE THREAD

**Issue by AsiiFR** [vsch/laravel-translation-manager#119]
Hello, 
After installation, i get a Call to undefined function Vsch\TranslationManager\getSupportedLocale() when i try to access a page.

Laravel 5.6 (Upgraded from 5.5, the package was working fine before upgrading but i had an issue because of PHP7.2, i couldn't publish files https://github.com/vsch/laravel-translation-manager/issues/113) and PHP 7.2
Thank you.
![screenshot_2](https://user-images.githubusercontent.com/28758292/39949709-cded96ce-557c-11e8-8587-17fe06554427.png)

**Comment by vsch** [comment]
@AsiiFR, sorry about that. Another reference to a function from my main project that I forgot to move to LTM helpers.

I will make a release with a fix in a few minutes to address this.

**Comment by AsiiFR** [comment]
Thank you for fast reply 👍

**Comment by vsch** [comment]
@AsiiFR, new version pushed. You are welcome.
