### ISSUE TITLE
Translation Import: Count always 0

### ISSUE THREAD

**Issue by ghost** [vsch/laravel-translation-manager#12]
Hello,

I want to import translations via `translations:import` command.

Always when I start these command, he doens't import something, because the count is always 0

I don't change config or other things.

Can u help `?

**Comment by vsch** [comment]
I will try it and let you know. I have not used the commands at all. These are left over from the original library.

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
on an fresh installation of laravel all works okay. with the translation files from https://www.dropbox.com/s/1x1wy2fhdmmvf0r/lang.zip?dl=0 nothing works!

**Comment by vsch** [comment]
BTW, thank you for reporting this. It did help uncover a bug in the new version that I will be releasing but the previous release 2.0.28 worked when I tried it with your lang.zip in an existing Laravel5 project. I also tried the import command, which uses the same functions as the web interface and it also worked.

When you go to the web interface of the translation manager (default route /translations) are you getting an error log? You need to have the debug mode enabled in `.env` file:

```
APP_DEBUG=true
```

That would help me see if there is a bug causing an exception.

Also can you send me your laravel-translation-manager.php configuration. You can remove any sensitive information, if you added any. I just want to try running it with your configuration.

**Comment by vsch** [comment]
@bihlmaierh, did you manage to make progress on this? Do you need any assistance?

New translation manager for Laravel 5.1 is available. It might have the issue fixes.
