### ISSUE TITLE
Add key button

### ISSUE THREAD

**Issue by chilio** [vsch/laravel-translation-manager#125]
I would like to add new key to all langs from ui and then translate it.
It is not very convenient to add new key manually.
Is it possible, or am I missing something?

**Comment by vsch** [comment]
@chilio, you only need to add a key to a single language, usually the primary locale. This makes the key available for translation in all other locales.

You can use the "Suffixed Key Operations" panel to add one or more keys.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/10299086/42975381-d499079a-8b89-11e8-89af-b9a3e3215bb6.png">

Then you can fill in the primary locale text for these keys and use the auto-translate button on the locale column to auto-translate these. <img width="112" alt="image" src="https://user-images.githubusercontent.com/10299086/42975388-e39f7ce2-8b89-11e8-9176-bd4fc14347e4.png">

The regex and filter radio buttons can be used to isolate the translation table to keys of interest based on key or status (new, missing, etc.)

BTW, the React UI has all the panels from WebUI available as Dashboards so you can select which ones you want to see on the page while working.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/10299086/42975456-362d8760-8b8a-11e8-83e0-502bb313bcac.png">

**Comment by chilio** [comment]
Thanks for the tip, that's exactly what I was looking for.
But Suffixed Key Operations along with Translation Helper greyed out...
So far I have not found a way to enable it.

**Comment by chilio** [comment]
@vsch  Ok got it.... 
But I don't understand why they are enabled with Yandex key.
Anyway thanks for your help and this great package....

**Comment by vsch** [comment]
@chilio, you need to get the Yandex key and put it into the LTM config file.

Yandex requires a key to allow access to the API. The key is free and you can get it at https://translate.yandex.com/developers

Once the key is defined in the LTM config file then all the translation related functionality is enabled.

**Comment by vsch** [comment]
@chilio, having automatic translation makes life a lot easier because you can use automatic translation to do the first run translations then tweak them. It is much easier than translating everything from scratch.

**Comment by chilio** [comment]
@vsch thanks I've noticed 👍 
However **I believe I've found a bug in react u**i (I suppose it is connected with caching/cookies in Suffixed Key Operations or Proceed do not ask.
To that moment everything was working fine and I could add keys without any problems.
Here is what I did using React UI:
1. Tried  adding key with :attribute in the key name like `test :attribute`
2. Clicked Proceed do not ask again
3. Unfortunately don't know which was first
4. But now adding keys does nothing, although it is functioning in base/standard ui
5. I've deleted all translations from db, reimported, logged from different browser and the problem still persists (I can edit translations, use Yandex....
**Hmm wait it comes down to `Proceed do not ask again`** I've also clicked on it and now I can't even publish - there is silently happening nothing, and all other functions with dialog are working normally.
Any ideas? Cause I am going to reinstall and not use `Proceed do not ask again`....

**Comment by chilio** [comment]
@vsch 
Second thing...
From what I see key names, cannot contain certain characters like (:,/,\) and for sure some others also.
Therefore validation against them is strongly suggested....

**Comment by vsch** [comment]
@chilio, you are right. It is an omission and I will add it to the error checking.

**Comment by vsch** [comment]
@chilio, I forgot to mention that if you click "Do not ask again" you can uncheck then under settings, the "Confirm ... " options:

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/10299086/43145200-d68e0b1c-8f2c-11e8-9157-033bee03a17f.png">
