### ISSUE TITLE
Problem with multiline translations while using rmariuzzo/laravel-localization-loader

### ISSUE THREAD

**Issue by chilio** [vsch/laravel-translation-manager#127]
I have a problem when translating multiline strings.
The package itself works as expected, but I use it with localization-loader for creating javascript translations via webpack.
So after I add new multiline translation it adds `<<<'PHP' ...` which breaks compilation in webpack.
I've asked also in localization-loader [here](https://github.com/rmariuzzo/laravel-localization-loader/issues/6#issuecomment-410454205)
Any suggestions regarding that?

**Comment by vsch** [comment]
@chilio, simplest solution is to add an option to always use double quotes for strings in language files.

It is really a limitation of laravel-localization-loader because it does not parse available PHP string syntax.

**Comment by vsch** [comment]
@chilio, I took a look at the code and found that the option is already there in the config. It has been a long time since I looked at that code. In LTM config find:

```php
    'export_format' => array(
        'PRESERVE_EMPTY_ARRAYS',
        //'USE_QUOTES',
        'USE_HEREDOC',
        'USE_SHORT_ARRAY',
        'SORT_KEYS',
    ),
```

Comment out `USE_HEREDOC` and remove comment in front of `USE_QUOTES`.

**Comment by chilio** [comment]
@vsch you are really MASTER.
Making config in front of the package, which covers this scenario, makes me to say WOW.
It works seemless now....
REALLY thank you for your help and superb fast reply....
BTW It would be great, if `laravel-localization-loader`, would be able to parse `HEREDOC` and by default render things down, but of course, it will be not of your concern....
