### ISSUE TITLE
open_basedir restriction in effect

### ISSUE THREAD

**Issue by MarisV** [vsch/laravel-translation-manager#129]
On stage environment, I can't import translations, I'm getting this error - 
`message": "file_exists(): open_basedir restriction in effect. File(/var) is not within the allowed path(s): (/var/www/clients/client2/web2/web:/var/www/clients/client2/web2/private:/var/www/clients/client2/web2/tmp:/var/www/cryptosided.com/web:/srv/www/cryptosided.com/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom)",
    "exception": "ErrorException",
    "file": "/var/www/clients/client2/web2/web/vendor/vsch/laravel-translation-manager/src/Classes/PathTemplateResolver.php",
    "line": 351, `

**Comment by vsch** [comment]
@MarisV, to operate properly this package requires write access to the laravel app's language directory during runtime. Otherwise there is no way to export language translations.

**Comment by MarisV** [comment]
@vsch Thanks for super fast answer. I tried to change access to resources folder ( even 0777 permissions), but with no luck, anyway I'm getting this error.

**Comment by vsch** [comment]
@MarisV, this is not a file system permission issue but php/web server restrictions.

It used to not scan the root `/` but that is not restrictive enough for most cases and should really be limited to the base path for the app.

I changed the code to only scan base_dir or directories under base_dir.

Made a new release with the fix. Please let me know if this fixes the issue.

**Comment by MarisV** [comment]
Excellent! Could this fix be applied for Laravel-5.5 branch as well? Cuz our project is using Laravel 5.5 version for now. Or it will be better if I'll create pull-request?

**Comment by vsch** [comment]
@MarisV, yes. I will update that branch also.

**Comment by vsch** [comment]
@MarisV, I updated all version 5 related branches 2.3, 2.4 and 2.5. Thank you for being patient.

**Comment by MarisV** [comment]
Ok, I updated local package. There was an error with '_str_starts_with_' ( function not found). For test purposes I changed to `starts_with` (laravel f-n), this error gone away, but old error occurred again =(`open_basedir restriction in effect`) =/. As I understand this happens when ` file_exists` or `is_dir` receives slash as param.
UPD. However, importing via console works perfectly
UPD2. I did small changes, and liven it up. Please check my pull-request, could it be a correct fix?

**Comment by vsch** [comment]
@MarisV, I updated the code for a logic error and changed the `str_starts_with` for `starts_with`, there was also a reversal of arguments to starts with.

Please let me know if this fix works for you so I can update 5.4 and 5.3 branches with the same fix.

**Comment by MarisV** [comment]
Great, finally it works ^^

**Comment by vsch** [comment]
@MarisV, thanks for the update.
