### ISSUE TITLE
Load lang files from locale subfolder

### ISSUE THREAD

**Issue by ClaudioVarandas** [vsch/laravel-translation-manager#13]
Hello,

This is not really a issue , its more a future improvement. The package only import files from root locale folder.

I check the code and it as to be refactored in several points, for now and because i have a tight dealine in my project im using underscores to organize my lang files.

I will try to get free time to pull the project and contribute to the project with lang and code, this is a great tool for any laravel project.

Thank you
CV

**Comment by vsch** [comment]
If I understand correctly the you mean that if you have `lang/en/some-directory/another/file.php` then it will not import that file.

If that is the case then it is a bug. I added this feature a while back and it worked but have not recently tried it after a lot of refactoring of code. I'll give it a try.

**Comment by ClaudioVarandas** [comment]
yes, thats it. I tested with lang/en/some-directory/file.php , I've checked the code and the package assumes a group from lang/en/{group} only.

**Comment by vsch** [comment]
The old code used to treat everything under root locale as group so `en/some-directory/another/file' would have group = 'some-directory.another.file'. 

I broke it when implemented the more flexible config. It is a bug and I'll fix it.

**Comment by vsch** [comment]
@kadinho, new version with loading translations from nested subdirectories fix. see [Version Info](https://github.com/vsch/laravel-translation-manager/blob/master/versioninfo.md)

Let me know if I broke something else. I am writing tests for the package but didn't get around to the file loading part yet.

**Comment by ClaudioVarandas** [comment]
@vsch Thx, i will test asap

**Comment by ClaudioVarandas** [comment]
@vsch Works fine :) Fixed!
