### ISSUE TITLE
PHP7 tempnam issue still releated in tag 2.3.12

### ISSUE THREAD

**Issue by juvenis** [vsch/laravel-translation-manager#144]
Laravel version : 5.3.31
Php version : 7.0.32
Package version : 2.3.12 (rn)

PHP7 fixes has been applied to system i know that but the situation still avaiable at that tag that i have to use. Could you please fix. Thank You.

issue lines : 
1 =>https://github.com/vsch/laravel-translation-manager/blob/4586515aff40ca30f69f5b4ee3f9198395cc008a/src/Manager.php#L1198

2 => https://github.com/vsch/laravel-translation-manager/blob/4586515aff40ca30f69f5b4ee3f9198395cc008a/src/Classes/TranslationFileRewriter.php#L122

3 => https://github.com/vsch/laravel-translation-manager/blob/4586515aff40ca30f69f5b4ee3f9198395cc008a/src/Classes/TranslationFileRewriter.php#L136

should all have "@" at the begining of the code

Best Regards

**Comment by vsch** [comment]
@juvenis, fixes for PHP 7 applied to branch 2.3, also applied the Windows directory path fixes because someone is bound to request that one in the future.

The fix for `count()` issue was applied as per other branches with code changed to:

		return !is_array($chars) || count($chars) === 1 ? $counts[0] : $counts;

Version 2.3.14 has these changes

**Comment by juvenis** [comment]
thank you so much for your kind answer. Nice work! :+1:
