### ISSUE TITLE
PHPstorm internal error

### ISSUE THREAD

**Issue by lmeyer1** [vsch/laravel-translation-manager#15]
I get many internal errors in PHPstorm:

> AssertionError: Already disposed: Project (Disposed) [projectname]

**Comment by vsch** [comment]
@lmeyer1 I think you are referring to idea-multimarkdown plugin for PhpStorm. The next release has this issue fixed, see vsch/idea-multimarkdown#47. You can also ignore this error, it happens when modifications are made to markdown files and the project is closed before the preview is updated.
