### ISSUE TITLE
Question: How to create a new group?

### ISSUE THREAD

**Issue by pmochine** [vsch/laravel-translation-manager#150]
I just don't see the button anywhere. Not even in your picture examples in Wiki  https://github.com/vsch/laravel-translation-manager/wiki/Web-Interface

**Comment by vsch** [comment]
Web UI does not create groups it only creates them on import. You can either create a file with a single key in the group that you want or set `log_missing_keys` to true in configuration to have any missing keys automatically created in the data base and these will show up as missing translations.

I think React UI does have create group but I cannot be sure if my memory serves me well on this.
