### ISSUE TITLE
Can't install this package for Laravel 5.0

### ISSUE THREAD

**Issue by protectedfor** [vsch/laravel-translation-manager#16]
Hello, after installing this package on laravel 5.0 I'm getting an error, when trying to locate to mysite/translations

```
FatalErrorException in /www/sbs.local/vendor/vsch/laravel-translation-manager/src/Controller.php line 368: Call to a member function all() on a non-object
```

maybe it because I'm using Laravel 5.0 instead of 5.1, or maybe I did something wrong?

**Comment by vsch** [comment]
@protectedfor, I went from Laravel 4.2 to 5.1 so never tried using it on Laravel 5.0. 

I checked the documentation and yes, Laravel 5.1 changed so lists() returns a collection and to get an array requires ->all() method call, in Laravel 5.0 this should be removed.

The change is in ManagerServiceProvider https://github.com/vsch/laravel-translation-manager/blob/master/src/ManagerServiceProvider.php#L14

Remove the ->all() from the end, just return $query as it is passed in, same as Laravel 4.2.

I can't promise that there are no other changes from 5.0 to 5.1 but they should not be major.
