### ISSUE TITLE
Can't see buttons like on screenshot

### ISSUE THREAD

**Issue by protectedfor** [vsch/laravel-translation-manager#18]
Hello, how am I should configure to display "publish", "zip all" and other button in my translation interface like on this screenshot: https://raw.githubusercontent.com/wiki/vsch/laravel-translation-manager/images/ScreenShot_main.png
My interface looks like: http://itmag.es/4cc0L

**Comment by vsch** [comment]
@protectedfor, please see #17, I gave a detailed description, including why you are missing most buttons.
