### ISSUE TITLE
Does it use table prefix?

### ISSUE THREAD

**Issue by Sennik** [vsch/laravel-translation-manager#21]
After installation and configuration using the package says the table ltm_translations does not exist. The table is migrated and available though. I use a table prefix in database.php mysql configuration (aaa_) so the physical name is aaa_ltm_translations. Works well all over Laravel 5.1 but not in this package?

The error:

``` mysql
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydatabase.ltm_translations' doesn't exist (SQL: SELECT * FROM ltm_translations WHERE `group` = AND locale IN ('en','fr','en','fr')
UNION ALL
SELECT DISTINCT
NULL id,
NULL status,
locale,
`group`,
`key`,
NULL value,
NULL created_at,
NULL updated_at,
NULL source,
NULL saved_value,
NULL is_deleted,
NULL was_used
FROM
(SELECT * FROM (SELECT DISTINCT locale FROM ltm_translations WHERE 1=1 AND locale IN ('en','fr','en','fr')) lcs
CROSS JOIN (SELECT DISTINCT `group`, `key` FROM ltm_translations WHERE `group` = AND locale IN ('en','fr','en','fr')) grp) m
WHERE NOT EXISTS(SELECT * FROM ltm_translations t WHERE t.locale = m.locale AND t.`group` = m.`group` AND t.`key` = m.`key`)
ORDER BY `key` ASC)
```

Also, I configured only one language at first in the primary_locale variable and the locales array: 'en'.

When I do php artisan translations:import I get:

```
Base table or view not found: 1146 Table 'mydatabase.ltm_translations' doesn't exist (SQL: SELECT * FROM ltm_translations WHERE locale = de AND `group` = auth
```

Where is the 'de' here and the 'fr' in the former example coming from?

**Comment by vsch** [comment]
@Sennik, the package does not use table prefix. The issue is in all the hand-rolled queries used to optimize database access over what eloquent provides. 

I'll take a look at the code. I don't think it will take a lot of work to add it in. I will give you an update shortly.

**Comment by Sennik** [comment]
Thanks!

**Comment by vsch** [comment]
@Sennik, new version published. I tested it using the alternative connections option in the Web UI by defining a new database connection with a prefix and creating a copy of the translations table with a prefix.

Not an extensive test but under the time constraints I could not do more. I am in the middle of a release for my IntelliJ idea-multimarkdown plugin and until it is done time is in short supply.

Let me know if you encounter other issues. I will make time to respond.

**Comment by Sennik** [comment]
Just pulled it in, importing works, screens work. Looks ok now. Thank you very much!
I will report any issues when they occur :-)

**Comment by vsch** [comment]
@Sennik, you are welcome and thank you for the request and the feedback on the fix.
