### ISSUE TITLE
Translation Work Orders: Allow users to access only some languages

### ISSUE THREAD

**Issue by Casinelli** [vsch/laravel-translation-manager#24]
I have a set of translators, each for a specific language (English to French, English to Japanese, etc.). It would be great if I could give each of them access only to those two (or more) set of languages, not every single one of them.

**Comment by vsch** [comment]
@Casinelli, for the moment there is no option to create translation work orders which would allow associating modification access for a set of Languages/Groups/Translation keys with a particular user.

I have considered adding this but it involves a lot of code modifications and questions regarding granularity of access. I would like to have a good idea of what is needed. Too much detail makes it a pain to use, too little does not solve the problem.
1. What is the level of granularity for modification access: by locale, by translation group or individual keys or all of the above as a mix?
2. Is there a need to limit modification only or also to limit view access? I don't see a use case for this can imagine someone might want to limit view access.
3. Should the primary locale be configurable as part of the work-order/user? In other words, is the primary locale from which translation is made system-wide, set in the work-order or can be changed by the individual doing the translation?

Originally the need for this package arose when I was delegating translations to a third party and I had actual use cases that the package needed to address. My current use of the translation manager is limited to myself doing the translations and mainly using it for eliminating hard-coded strings in the application. This does not give me much insight into real-world translation management problems.

Any input from someone who actually hires/delegates translations to someone else would be greatly appreciated.

**Comment by Casinelli** [comment]
I can tell you for what regards to me right now. I'll need to translate the website in many different languages, and hire a translator that will do the translations for one language (usually over a period of 1-2 weeks). After that he/she might also come back monthly do update new strings.

**1. What is the level of granularity for modification access: by locale, by translation group or individual keys or all of the above as a mix?**

What I _really_ wouldn't want is a translator altering the translations for the primary language (English), so that should be somehow _locked_. Less bad, but still important, would be to be able to set an array of languages the translator is allowed to translate, say `['it', 'jp']`, and he/she would be able to only select those in the interface. I don't see an use case for going down to individual keys.

**2. Is there a need to limit modification only or also to limit view access? I don't see a use case for this can imagine someone might want to limit view access.**

I don't see a need to limit view access. I can imagine one day not wanting to show translations for, say, the admin panel. In that case having a regexp for "excluded views" would be useful (e.g. so it can be set to something like `^admin\.[a-z0-9\.]*`). But again it's probably not a super important feature (for me right now at least).

**3. Should the primary locale be configurable as part of the work-order/user? In other words, is the primary locale from which translation is made system-wide, set in the work-order or can be changed by the individual doing the translation?**

I guess having the translators being able to choose the primary locale is an advantage, and I can't see an upside in not having the possibility. For example one of the translators might be Japanese, but only know Spanish instead of English. In that case would be useful if they can set their own primary language (as long as they're not allowed to edit it, as per point one).

**Comment by vsch** [comment]
@Casinelli, Added per locale user access management. See [Enabling per locale user access control](../wiki/Configuration#enabling-per-locale-user-access-control)

Basic functionality and UI. Nothing to brag about, but does the job.

as a collapsed accordion when a group is selected, to keep out of the way

<img width="953" alt="screen shot 2016-04-16 at 7 49 32 pm" src="https://cloud.githubusercontent.com/assets/10299086/14584331/b792962e-040f-11e6-873f-5ab60f5ad832.png">

or when no group is selected then it shows as a panel

<img width="925" alt="screen shot 2016-04-16 at 8 14 21 pm" src="https://cloud.githubusercontent.com/assets/10299086/14584336/d884acaa-040f-11e6-8da5-f0da637aa6d6.png">
