### ISSUE TITLE
Delete button not working for some keys

### ISSUE THREAD

**Issue by Casinelli** [vsch/laravel-translation-manager#25]
I have some **keys** in which the delete button doesn't seem to work. Admittedly they are old keys that include spaces and other characters, but that's also the reason I'm trying to delete them.

For these keys it selects the row (highlights when clicking the trash button), but even after "publishing" the rows are still there:
- Website/Blog URL:
- Would you be interested in reviewing our new set of hosts in your location or when you travel?

For this key the row doesn't even highlight when clicking on the trash button:
- As our affiliate partner, you can earn a 50% commission share of our booking fee on all qualifying bookings. We know that the travel season is seasonal, so apart from a long cookie length, you will also get paid a fixed rate for every sign

In this case the key was actually longer, but it's cut at this length on the interface. Maybe it's some mismatch between the max key length in the database and the one shown on the interface?

**Comment by vsch** [comment]
@Casinelli, keys are passed as URL parameters so I suspect there is a lack of proper URL encoding. I will look into it but for now the only way to delete these keys is directly through SQL via a console.

**Comment by vsch** [comment]
@Casinelli, updated to version 2.0.37 with fix for keys containing characters that need URL encoding.

Had to double URL encode/decode to get around Laravel URL decoding before routing. I think this is a Laravel bug but this has been the behaviour for quite a long time.
