### ISSUE TITLE
name of DB connection should be defineable in config file - feature request

### ISSUE THREAD

**Issue by UnrulyNatives** [vsch/laravel-translation-manager#28]
as in title

Consider this case: 
I have several projects which use common DB for some data, translations among them.

I have my translation table in DB in a connection named `translate_database`

in the barryvdh package I was forced to edit file `src/Models/Translation.php` in `vendor` folder:

```
protected $table = 'translate_database.ltm_translations';
```

**Comment by vsch** [comment]
@UnrulyNatives, config option for database name added.

See: https://github.com/vsch/laravel-translation-manager/blob/2.0.40/config/laravel-translation-manager.php#L144-L174

Now migrations would need to be manually modified for the name change. I did not yet address these.

Let me know if it works for you.

**Comment by vsch** [comment]
@UnrulyNatives, had to change the way the database name is changed for translations. Now you need to define another connection name that has the desired database as default and then define that as the default connection to use for the translation manager.

Laravel does not consistently handle database name change on a connection. Previous implementation resulted in inconsistent functionality. See [Changing the database name](../wiki/Configuration#changing-the-database-name)

Added per locale user access management. See [Enabling per locale user access control](../wiki/Configuration#enabling-per-locale-user-access-control)
