### ISSUE TITLE
mismatch in class names

### ISSUE THREAD

**Issue by UnrulyNatives** [vsch/laravel-translation-manager#30]
IT seems that you have a bug in this commit: https://github.com/vsch/laravel-translation-manager/commit/fb5b0b759dd695614ea2b0f42e9967c0718a3152

In one place tere we see: $router->pushMiddlewareToGroup('web', 'Vsch\TranslationManager\RouteAfterMiddleware');
an in the file  src/RouteAfterMiddleWare.php the class `class RouteAfterMiddleWare`

The names don't match: `RouteAfterMiddleware` vs `RouteAfterMiddleWare`

Peter

**Comment by vsch** [comment]
@UnrulyNatives, thank you. My dev system is OS X which has a case insensitive file system. Got caught a few times with file name case mismatches.

I'll fix it and make a new release.

**Comment by vsch** [comment]
@UnrulyNatives, version 2.1.1 released. Thank you for the heads up.

**Comment by UnrulyNatives** [comment]
at your service - Stansfield
