### ISSUE TITLE
Edit In Place Sample

### ISSUE THREAD

**Issue by vsch** [vsch/laravel-translation-manager#34]
![ltm-editinplace](https://cloud.githubusercontent.com/assets/10299086/15326218/29c1cdd2-1c1b-11e6-9781-9e0359e858de.gif)

**Comment by vsch** [comment]
Instruction added to mods needed to enable in place translation edit on site pages: https://github.com/vsch/laravel-translation-manager/wiki/Configuration#enabling-edit-in-place-on-site-pages

**Comment by ghost** [comment]
I loved this functionality. Well done!!!
Although the the  Lang::inPlaceEditing(true) is not persisting trhough requests in Laravel 5.2.
I am guessing this is related with the web middleware that now is set as default.

I tried to remove this middleware in the config with no success... Thoughts?

**Comment by vsch** [comment]
@leobeal-git, it is stored in the session but it is only restored if you call \Lang::inPlaceEditing() with no parameter.

You need to add this call somewhere in your middleware or service provider that is loaded before handling a request. That way this setting will be restored from the session.

**Comment by ghost** [comment]
that was quick! Working like a charm now!!!
Did I miss this part or it's not in the how to?

Thanks a lot!

**Comment by vsch** [comment]
@leobeal-git, I missed this part. I'll add it to the wiki.

**Comment by yurtesen** [comment]
Hmm... I did something much more simple and it seems to be working. In my app.blade.php I have added. (in the dropdown area as an additional link)

```
                                @if (Auth::user()->hasRole('translator'))
                                    <li>
                                        <a href="{{ url('/'.config('laravel-translation-manager.route')['prefix'].'/toggle-in-place-edit') }}">
                                                <i class="fa fa-btn fa-language"></i>{!! ucwords(trans('translatekey')) !!}
                                        </a>
                                    </li>
                                @endif
```

Now I am able to just click on it to enable/disable in place editing. Since I already check if user had translator role in middleware Authenticate, I do not need to do add more code...

```
        if ($request->is('translations') || $request->is('translations/*')) {
            if (Auth::guard($guard)->check()) {
                /* @var $user User */
                $user = Auth::guard($guard)->user();
                if (!$user->hasRole('translator')) {
                    App::abort(403);
                }
            }
        }
```

Also for some reason @if(inPlaceEditing()) seems to work in blade templates, why do we need Lang::inPlaceEditing() ? (is it even normal that it works on my site?)

and where is the functions from inflection.js are used? I couldn't find anything from it in the js codes?

Thanks!

**Comment by vsch** [comment]
@yurtesen, LTM has a global function inPlaceEditing() which calls \Lang::inPlaceEditing()

Your simpler solution is best. I forgot that I added the LTM toggle-in-place-editing handler.  I will update the wiki for the simpler option.

**Comment by yurtesen** [comment]
Here is a pull request for alternative edit in place which require less modification to templates... feel free to review
https://github.com/vsch/laravel-translation-manager/pull/43
