### ISSUE TITLE
ManagerServiceProvider is not deferred

### ISSUE THREAD

**Issue by yurtesen** [vsch/laravel-translation-manager#36]
I see that ManagerServiceProvider does have
`protected $defer = false;`
Shouldn't this be set to true since we wont be using it unless somebody is accessing the translations url?

On a side note, what is the best way to restrict access to /translations url using laravel permissions ? make a middleware for it?

**Comment by vsch** [comment]
@yurtesen, I changed the $defer to true for the next release.

Yes, you need authentication middleware to control access to the translation web UI and add it to the config file to the `'route'['middleware']` setting. By default it uses `'auth'`middleware.

**Comment by yurtesen** [comment]
Yes, I think this was changed a bit in Laravel 5.2 because people could use 'before' route option earlier apparently. If anybody finds this post, below is what I came up with in auth middleware (thought about making separate middleware too but this was faster)

Below is how I implemented this in authenticate middleware, feel free to add  it to documentation as an example:

Notice: The hasRole function should be impemented/replaced by the developer.

```
        if ($request->is('translations') || $request->is('translations/*')) {
            if (Auth::guard($guard)->check()) {
                /* @var $user User */
                $user = Auth::guard($guard)->user();
                if (!$user->hasRole('translator')) {
                    App::abort(403);
                }
            }
        }
```

**Comment by vsch** [comment]
@yurtesen, thanks I'll add it as a sample.

BTW, middleware is easy to create. 
1. Copy the  app/Http/Middleware/Authenticate.php and modify the conditions. 
2. Add the new middleware to route middleware in  app/Http/Kernel.php 
3. Change the route middleware for translations in ltm configuration to the new middleware
