### ISSUE TITLE
CSRF problem with inline editing and more...

### ISSUE THREAD

**Issue by yurtesen** [vsch/laravel-translation-manager#37]
I realized that the CRSF interferes with inline editing. You can't post anything because it is enabled by default. This was not mentioned in the translation manager documentation

I had to add it to $except variable in VerifyCsrfToken middleware. I did this programmatically so the value reflects the conf value of the translation manager.

```
    public function __construct(Application $app, Encrypter $encrypter)
    {
        $this->except[] = config('laravel-translation-manager.route')['prefix'] . '/*';
        parent::__construct($app, $encrypter);
    }
```

In addition, I needed to add additional css/javascript files to enable in place editing.

```
    @if(inPlaceEditing())
        <link href="{{ url('/vendor/laravel-translation-manager/css/translations.css') }}" rel="stylesheet">
        <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
        <script src="{{ url('/vendor/laravel-translation-manager/js/translations.js') }}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
    @endif
```

I wonder if the translation package can have functions such as getInPlaceEditingCss() , getInPlaceEditingScripts() so one can just include these in the blade templates and they would output the correct contents if in place editing is enabled?

Also I found out that using blade template structures such as  {{ trans('mybutton') }} is breaking the page code since the templating engine escapes the html characters. But {!! trans('mybutton') }} seem to work fine (at least as far as I tested). Whereas the LTM blade templates use PHP code only and does not use the blade templeting engine features?
I think there should be some example on what are best practices when creating the templates for a site. ???
PS. I now figure that the answer to the last question is using ifEditTrans and noEditTrans. But this is not very user friendly because it breaks the page, isnt it? (or am I wrong?)

Thanks!

**Comment by vsch** [comment]
@yurtesen, I did the edit in place quickly and left out a few details since they are already in my project.

You need to add this to your master layout head section:

``````
```html
<meta name="csrf-token" content="{{ csrf_token() }}"/>
```
``````

and then there is no need to create exception for CSRF. LTM webpage uses CSRF.

I am updating the wiki.

**Comment by yurtesen** [comment]
Yes, that seems to work also per the laravel manual:
https://laravel.com/docs/master/routing#csrf-x-csrf-token
But I wonder if it can cause some issues with caching in future. If there is different token for every page load. Seems a bit unnecessary too. (I didnt test caching features yet in laravel so I dont know for sure).

**Comment by vsch** [comment]
@yurtesen, the CSRF token is generated for every page. That is how it is done for all forms anyway. Specifying it in the page head allows JavaScript to access it so it can be used in AJAX requests. 

Caching a page will cause problems because the token will expire. Your solution to exclude CSRF checking for translation URLs is a solution to the caching problem.
