### ISSUE TITLE
Small bug in ifEditTrans

### ISSUE THREAD

**Issue by yurtesen** [vsch/laravel-translation-manager#39]
The helper function ifEditTrans is making a call:

`$trans->getInPlaceEditLink($key, $parameters ?: [], $locale, $useDB, $origtext);`

but the getInPlaceEditLink takes different arguments:

`function getInPlaceEditLink($key, array $replace = array(), $locale = null, $withDiff = null, $useDB = null, $origtext=null)`

Notice withDiff argument is missing from call...

**Comment by vsch** [comment]
@yurtesen, good catch. I updated the function for next release.

``` php
    function ifInPlaceEdit($text, $replace = [], $locale = null, $useDB = null, $noWrap = null)
    {
        /* @var $trans Translator */
        $trans = App::make('translator');
        if ($trans->inPlaceEditing()) {
            while (preg_match('/@lang\(\'([^\']+)\'\)/', $text, $matches)) {
                $repl = $trans->getInPlaceEditLink($matches[1], $replace, $locale, $noWrap, $useDB);
                $text = str_replace($matches[0], $repl, $text);
            }
            return $noWrap ? $text : "<br>[$text]";
        }
        return '';
    }
```
