### ISSUE TITLE
Compatibility with Laravel 5.3

### ISSUE THREAD

**Issue by UnrulyNatives** [vsch/laravel-translation-manager#40]
Do we need to wait or your package can be adjusted now?

At this moment when installing the package I end up with dependency failure: `symfony/finder`

Thx

**Comment by vsch** [comment]
@UnrulyNatives, I am not able to update the package dependency at this time because one of its dependencies laravelcollective/html requires laravel/framework 5.2.x.

**Comment by kschrute** [comment]
@vsch there is laravelcollective/html 5.3 available. Can you update the dependency?
