### ISSUE TITLE
Call to undefined method inPlaceEditing

### ISSUE THREAD

**Issue by loranger** [vsch/laravel-translation-manager#42]
Hello,

I think the last update broke my LTM.
I did export the new migrations and migrate
Now, as soon as I try to reach my translation manager, I get a fatal error :

```
FatalThrowableError in helpers.php line 114:
Call to undefined method Illuminate\Translation\Translator::inPlaceEditing()
```

Did I miss something in the install/upgrade process ?

**Comment by yurtesen** [comment]
Are you sure you have the correct configuration in your app.php

```
        Vsch\TranslationManager\ManagerServiceProvider::class,
        Vsch\TranslationManager\TranslationServiceProvider::class,
```

See: https://github.com/vsch/laravel-translation-manager/wiki/Installation

**Comment by vsch** [comment]
@loranger, it looks like translator service is not replaced by one provided by LTM and is still the original one.

Check out step 2. of [Installation](https://github.com/vsch/laravel-translation-manager/wiki/Installation)

Please verify that the config/app.php still has the changes needed to use the LTM provided translation service.

**Comment by loranger** [comment]
Thanks for your replies,

I used to use the v 2.0 which worked perfectly. Thus, the official translator service was already replaced by the service providers of your (awesome, by the way) package :

``` php

    'providers' => [
        ...
        //Illuminate\Translation\TranslationServiceProvider::class,
        Vsch\TranslationManager\ManagerServiceProvider::class,
        Vsch\TranslationManager\TranslationServiceProvider::class,
        ...
    ],
```

And those are the only two occurences of `Vsch` inside my `app.php`since I did remove the now useless `UserPrivilegeMapperServiceProvider`.

**Comment by yurtesen** [comment]
If you DID NOT comment out this line:
`Illuminate\Translation\TranslationServiceProvider::class,`
and if it is after 
`Vsch\TranslationManager\TranslationServiceProvider::class,`
it will still override the vsch/ltm translation service provider class. and you will get this error. If this is not your problem, then I think we need more information because I can't really think about anything else...

**Comment by loranger** [comment]
The providers array sample above is a copy-paste from my app.php, but you are right, this was the problem :

I now uses https://github.com/overtrue/laravel-lang and his service provider was overriding your. I did switch the order and the translation manager now works. I suppose Overture does not anymore...

``` php
    'providers' => [
        ...
        //Illuminate\Translation\TranslationServiceProvider::class,
        Overtrue\LaravelLang\TranslationServiceProvider::class,
        Vsch\TranslationManager\ManagerServiceProvider::class,
        Vsch\TranslationManager\TranslationServiceProvider::class,
        ...
    ],
```

Thanks for your package and for your support !
