### ISSUE TITLE
I cant see the buttons for publishing etc and importing etc?

### ISSUE THREAD

**Issue by filipveschool** [vsch/laravel-translation-manager#46]
Hi on your webinterface I can only see this see image included please.

![image](https://cloud.githubusercontent.com/assets/17187296/17318995/e5aa4b72-588a-11e6-9c08-5b2836e3758a.png)

How can I get the other buttons to see please? I dont know what I do wrong?

**Comment by vsch** [comment]
@filipveschool, translation administration is not enabled for the user. The 'admin_enabled' setting in the config file is set to true by default, you also need to provide for mapping user names to their permissions. See [Installation: Setting Up User Authorization](https://github.com/vsch/laravel-translation-manager/wiki/Installation#setting-up-user-authorization)
