### ISSUE TITLE
Class 'Translator' not found

### ISSUE THREAD

**Issue by ghost** [vsch/laravel-translation-manager#50]
laravel 5.3
FatalThrowableError in web.php line 66: 
Class 'Translator' not found in
Route::group(['middleware' => 'web', 'prefix' => 'translations'], function () {
    Translator::routes();
});

**Comment by vsch** [comment]
@AlehDev do you have a `use Vsch\TranslationManager\Translator;` in your web.php?

**Comment by ghost** [comment]
@vsch Sorry  :+1:   по старинке... спасибо!!!

**Comment by vsch** [comment]
@AlehDev, не за что.

**Comment by loranger** [comment]
Maybe you should add this `use` recommandation in the documentation because there is no mention about any `Translator` class anywhere...

**Comment by vsch** [comment]
@loranger, updated installation instructions. Missed it because I use PhpStorm which has a convenient automatic import.

Added to Installation wiki.

**Comment by loranger** [comment]
Thank you so much. I think this will be helpful.
