### ISSUE TITLE
Missing `use_cookies` configuration

### ISSUE THREAD

**Issue by arcanedev-maroc** [vsch/laravel-translation-manager#55]
The config file is missing a `use_cookies` with a boolean value.

Source: https://github.com/vsch/laravel-translation-manager/blob/master/src/Translator.php#L502

If the `use_cookies` is not specified, it will always return `laravel-translation-manager::` and it break the logic for other packages.

**Comment by vsch** [comment]
@arcanedev-maroc, thank you for noticing this. It was a typo, the default value should be true.

Fixed and pushed updated version.
