### ISSUE TITLE
More than 5 translations "freeze up" 

### ISSUE THREAD

**Issue by kantorcodes** [vsch/laravel-translation-manager#56]
Hi,

When I attempt to use the auto fill or auto translate functions in the backend and there are more than 5 in the queue, they seem to freeze up like so: 

http://prntscr.com/dnoz8k

I usually have to reboot FPM after this 

Any clues how to fix this error?

**Comment by vsch** [comment]
@mikenolimits, you can change the JS to only do one at a time. The code that determines that is https://github.com/vsch/laravel-translation-manager/blob/master/public/js/translations_page.js#L451-L453

If you just leave the `fireTranslate()` without the loop.

Is there something that would have an issue with handling concurrent requests? Database connection limit, etc.

The auto-translate gets the translation from Yandex, then makes a request to LTM controller to set the translation. Each one winds up being a separate request.

**Comment by kantorcodes** [comment]
I will give that a shot and let you know if it works -- for reference my dev and production environment was php7.0 on laravel forge and laravel homestead.

**Comment by vsch** [comment]
@mikenolimits, I also use php 7.0 for dev but php 5.6 for prod on AWS. 

I don't use laravel forge or homestead. When I started with Laravel 4.2 I could not get homestead working so I learned to roll my own and can't be bothered to switch now. I get enough app breaking changes from Laravel version updates, would not want the dev environment to have the same issues.

**Comment by kantorcodes** [comment]
Thank you @vsch that solution appears to have worked. Not entirely sure why though!

**Comment by vsch** [comment]
@mikenolimits, not sure why it worked or why there was a problem in the first place?
