### ISSUE TITLE
Load events after the ajax call in edit in place.

### ISSUE THREAD

**Issue by Alorse** [vsch/laravel-translation-manager#57]
Hello, I'm using the edit in place and it works fine, but it does not do it when adding elements to the DOM after some Ajax request or loading a component in ReactJS.

What happens is that the click event of jquery does not propagate to new elements after having rendered the DOM.

Could you help me with this?

**Comment by Alorse** [comment]
I found the solution, just need to call the following function.
`$('.vsch_editable').vsch_editable();`

**Comment by vsch** [comment]
@Alorse, glad you found it and it is the right solution so that new elements are hooked into the editable handling.
