### ISSUE TITLE
5.4

### ISSUE THREAD

**Issue by nam-co** [vsch/laravel-translation-manager#60]
Hi, thanks for the work, does this package work in 5.4?

**Comment by vsch** [comment]
@nam-co, I have not upgraded my dev environment to 5.4 so cannot say. It depends on breaking API changes in 5.4 compared to 5.3.

**Comment by nam-co** [comment]
thanks for the response, can please allow 5.4, according to this https://twitter.com/themsaid/status/821997593668554752 must packages work

**Comment by vsch** [comment]
@nam-co, I am upgrading to 5.4 now. There were some required changes since I have not update some old code for a while. 5.4 removed support for it. Not much but still needs to be validated.

I'll post an update once I release the 5.4 compatible version.

**Comment by vsch** [comment]
@nam-co, cannot update to 5.4 right now because LTM depends on laravelcollective/html and it only supports 5.3.

So to answer your original question, no it does not support 5.4, and probably will not until 5.4 is stable.

**Comment by Casinelli** [comment]
@vsch laravelcollective/html has updated to 5.4 now. Anything else missing?

**Comment by vsch** [comment]
@Casinelli, thank you for the update. I will give the migration another try and make a release or let you know if there is something else missing. I already addressed the deprecated methods so I expect only external dependencies to be the hold up.

**Comment by vsch** [comment]
5.4 support added to Version 2.4.0, released.
