### ISSUE TITLE
Add a note that only MySQL connection is supported

### ISSUE THREAD

**Issue by Aareksio** [vsch/laravel-translation-manager#66]
You may want to add a note on the wiki (and possible in README), that only MySQL connection is supported and/or add connection type check in the code. 

Using sqlite database (Laravel isn't the core of my app, so I didn't want it to manage migrations in main database), I spend a lot of time trying to figure out why `php artisan translation:import` outputs `Done importing, processed XXX items!` and my sqlite database stays empty. Worth noting is that `php artisan translation:find` worked, although the web interface didn't display the keys properly.

The only note about MySQL dependency I found in the repository was in #4.

**Comment by vsch** [comment]
@Aareksio, I will update the readme to reflect this limitation.
