### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by ghost** [vsch/laravel-translation-manager#71]
Если можно, я на русском... :)
local.ERROR: ErrorException: Trying to get property of non-object в файле:
src/Classes/TranslationFileRewriter.php:228

$stringData = [];
                $arrayState = array_pop($arrayStack);
                $stringData['quotes'] = $arrayState->arrayType;
                $inArray--;
                continue;
            }

Происходит это только с 1 файлом группы при нажатии на Publis Group,
ну как бы для меня не критично, но...
Lara 5.4 с php 7.1
Спасибо!

**Comment by vsch** [comment]
@trixanapp, no problem with using Russian. If you don't mind I'll answer in English because my typing is excruciatingly slow in Russian.

It happens on encountering `)` or `]` but no array opening `(` or `[` was encountered.

I added a check to make sure there is an element on the stack.

It is a parser error. It would be much easier if you could provide a sample file that causes this issue so I can verify that I dealt with the real issue or a symptom of some other bug.

**Comment by ghost** [comment]
Хорошо! Спасибо! Я читаю английский.
Вот образец файла, я его перевожу на русский:
`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Exception Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used in Exceptions thrown throughout the system.
    | Regardless where it is placed, a button can be listed here so it is easily
    | found in a intuitive way.
    |
    */

    'backend' => [
        'access' => [
            'roles' => [
                'already_exists'    => 'That role already exists. Please choose a different name.',
                'cant_delete_admin' => 'You can not delete the Administrator role.',
                'create_error'      => 'There was a problem creating this role. Please try again.',
                'delete_error'      => 'There was a problem deleting this role. Please try again.',
                'has_users'         => 'You can not delete a role with associated users.',
                'needs_permission'  => 'You must select at least one permission for this role.',
                'not_found'         => 'That role does not exist.',
                'update_error'      => 'There was a problem updating this role. Please try again.',
            ],

            'users' => [
                'cant_deactivate_self'  => 'You can not do that to yourself.',
                'cant_delete_self'      => 'You can not delete yourself.',
                'cant_restore'          => 'This user is not deleted so it can not be restored.',
                'create_error'          => 'There was a problem creating this user. Please try again.',
                'delete_error'          => 'There was a problem deleting this user. Please try again.',
                'delete_first'          => 'This user must be deleted first before it can be destroyed permanently.',
                'email_error'           => 'That email address belongs to a different user.',
                'mark_error'            => 'There was a problem updating this user. Please try again.',
                'not_found'             => 'That user does not exist.',
                'restore_error'         => 'There was a problem restoring this user. Please try again.',
                'role_needed_create'    => 'You must choose at lease one role.',
                'role_needed'           => 'You must choose at least one role.',
                'update_error'          => 'There was a problem updating this user. Please try again.',
                'update_password_error' => 'There was a problem changing this users password. Please try again.',
            ],
        ],
    ],

    'frontend' => [
        'auth' => [
            'confirmation' => [
                'already_confirmed' => 'Your account is already confirmed.',
                'confirm'           => 'Confirm your account!',
                'created_confirm'   => 'Your account was successfully created. We have sent you an e-mail to confirm your account.',
                'mismatch'          => 'Your confirmation code does not match.',
                'not_found'         => 'That confirmation code does not exist.',
                'resend'            => 'Your account is not confirmed. Please click the confirmation link in your e-mail, or <a href="'.route('frontend.auth.account.confirm.resend', ':user_id').'">click here</a> to resend the confirmation e-mail.',
                'success'           => 'Your account has been successfully confirmed!',
                'resent'            => 'A new confirmation e-mail has been sent to the address on file.',
            ],

            'deactivated' => 'Your account has been deactivated.',
            'email_taken' => 'That e-mail address is already taken.',

            'password' => [
                'change_mismatch' => 'That is not your old password.',
            ],

            'registration_disabled' => 'Registration is currently closed.',
        ],
    ],
];`

**Comment by vsch** [comment]
@trixanapp, thank you. I will try it to see where it is messing up.

**Comment by ghost** [comment]
Ok! Thanks!

**Comment by vsch** [comment]
@trixanapp, the fix does fix the issue but the cause is the line:

```php
'resend' => 'Your account is not confirmed. Please click the confirmation link in your e-mail, or <a href="'.route('frontend.auth.account.confirm.resend', ':user_id').'">click here</a> to resend the confirmation e-mail.',
```

With the fix the group will be exported but the dynamic value `route('frontend.auth.account.confirm.resend', ':user_id')` will be replaced with a fixed value which is not what you want.

The only solution at the moment is to either change the dynamic value to a variable that is provided to translation API or to exclude this file from LTM editing, for example if the file is named `test.php` then it's group is `test` the following addition to laravel-translation-manager.php will remove it from available groups in LTM and prevent it from being overwritten on `Publish`:

```php
/**
 * Exclude specific groups from Laravel Translation Manager.
 * This is useful if, for example, you want to avoid editing the official Laravel language files.
 *
 * @type array
 */
'exclude_groups' => array(
    'test',
),
```

**Comment by ghost** [comment]
Здравствуйте.
Спасибо! Этот отрывок кода, так очевидно...
Надо же разделять тэги, код от строк перевода,
Я обычно всегда разделяю.
Здесь я вызвался помочь переводом на русский интерфейс проекта laravel-5-boilerplate.
В общем, буду им рекомендовать изменить логику.
Вам лично огромное спасибо за проект.

**Comment by vsch** [comment]
Пожалуйста. Этот проект был создан для перевода с английского на русский. До него я заморочился с интеграции переводов от переводчиков. Особенно когда они переводили переменные в тексте `:user_id`. После автоматизации переводы перестали занимать мое время.
