### ISSUE TITLE
$locales array elements need to be filtered before passing to view

### ISSUE THREAD

**Issue by NassarX** [vsch/laravel-translation-manager#72]
Sometimes I get a list of locales with one blank on primary & translate select, clearing browser cookies fix that so after following code found that line 
`        $translatingLocale = \Cookie::get($this->cookieName(self::COOKIE_TRANS_LOCALE), $currentLocale);`  in  **loadlocales()** function cause the problem here as **Cookie::get** return empty value.

**Comment by vsch** [comment]
@NassarX, thanks for the report. I will fix it for the next release. The actual bug/fix is to add a test for current locale not being set with the code:

```
        if (!$currentLocale) {
            $currentLocale = $primaryLocale;
        }
```

**Comment by vsch** [comment]
@NassarX, forgot to mention that this makes sure that all locales are not blank before the array is created. Primary locale will be a cookie value, primary locale in config and `en` as the last fail safe if the other two are not defined.

**Comment by NassarX** [comment]
Thanks @vsch  it works now
