### ISSUE TITLE
log_missing_keys working even if set to false

### ISSUE THREAD

**Issue by Jaume007** [vsch/laravel-translation-manager#77]
I have my config file set like this:
`/**
     * determines whether missing keys are logged
     *
     * @type boolean
     */
    'log_missing_keys' => false,

    /**
     * determines whether usage of keys is logged, requires missing keys to be logged too
     *
     * @type boolean
     */
    'log_key_usage_info' => false,
`
If on a template there's a key that's not defined on any lang file the key is logged on the database.  Even with log_missing_keys set to flase

**Comment by vsch** [comment]
@Jaume007, thank you for bringing this up. I will take a look at the code. It is very possible that some recent modifications  fail to check the configuration flag.

**Comment by vsch** [comment]
@Jaume007, found 2 locations where the keys would be logged regardless of settings. Will make a release shortly.

**Comment by Jaume007** [comment]
Hi,
Thanks for looking into the issue. 
Today I tried to install ltm but when I edit the app.php file I have this error when trying to do a php artisan:

`[ErrorException]                            
  array_merge(): Argument #2 is not an array `

I don't know which file has the error but when I comment the changes on app.php it works again.

**Comment by vsch** [comment]
@Jaume007, can you enable debug mode so you can see a stack trace of the error to give detailed information of where the error occurs?

You can do it in .env file with a line `APP_DEBUG="true"`
