### ISSUE TITLE
Extend translate functions in find command

### ISSUE THREAD

**Issue by Snake231088** [vsch/laravel-translation-manager#82]
Please add the possibility to extend translate functions array from config file in findTranslation method on the Manager.php so i can add my translation function that i used in my projects.
Sorry for my English!

**Comment by vsch** [comment]
@Snake231088, I do not understand what you mean. 

Could you please give me an example of what you want to achieve.

I can also communicate in Russian or French. If you are more comfortable in communicating in these languages.

**Comment by vsch** [comment]
@Snake231088, this was added by @vesper8 in #114
