### ISSUE TITLE
Call to undefined method Vsch\TranslationManager\Translator::routes()

### ISSUE THREAD

**Issue by uaibo** [vsch/laravel-translation-manager#84]
I'm getting this error:
Call to undefined method Vsch\TranslationManager\Translator::routes()
https://i.gyazo.com/f6884d38d1734eade0585bf0293b24c0.png

My routes.php:
https://i.gyazo.com/dcac53fddd96b26bfa5d0280bb277d33.png

Service providers: 
https://i.gyazo.com/c6a6ff09f1424ea0a6055484667c23ca.png

Composer:
https://i.gyazo.com/3ad0d97be47d7c4e8d4288c76ad54e00.png
https://i.gyazo.com/b9b849b8170d69bf77c4c04355f88053.png

I have followed this guide to install 
https://github.com/vsch/laravel-translation-manager/wiki/Installation
but even after several tries, I keep getting that same error;

any idea what to do?

Thanks.

**Comment by vsch** [comment]
@smartsal, you are using Laravel 5.2 the last version which was used with 5.2 is 2.1.4. Can you confirm which LTM version are you installing?

**Comment by uaibo** [comment]
I just changed composer.json to use version "~2.1"
https://i.gyazo.com/2cea41ba700c57afbd994c1b10958119.png

(even completely deleted "vsch" folder from vendors)
and ran composer update. so I believe version ~2.1 should be installed now.
still getting the same exact error: 
https://i.gyazo.com/2df2f6180f55e79addf756fc661ba00e.png

when I check this file "\vendor\vsch\laravel-translation-manager\src\Translator.php" there is no routes() method. shouldn't there be a "routes()" method ?

**Comment by vsch** [comment]
@smartsal, there was a change in routing from 5.1/5.2 to 5.3/5.4. The routes were modified by the LTM package without you needing to add anything to your routes, if memory serves me.

The installation instructions which were in effect when 2.1.4 was updated should be used: https://github.com/vsch/laravel-translation-manager/wiki/Installation/3708e8a61d3c1a20b3c4ffca59830fd10221b7c5

**Comment by uaibo** [comment]
Aaah that fixed it, thanks. Indeed it was already fixed as you said (because I didn't have to modify the routes) but following step 7 in https://github.com/vsch/laravel-translation-manager/wiki/Installation
https://i.gyazo.com/807c3723990d152e7846c4313c46288e.png I modified it and then got confused. 

So to conclude, anybody else who is using Laravel 5.2 use this guide for installation https://github.com/vsch/laravel-translation-manager/wiki/Installation/3708e8a61d3c1a20b3c4ffca59830fd10221b7c5 (and use "vsch/laravel-translation-manager": "~2.1" in your composer.json config.

Thanks for taking the time to reply and for making a great translator :)

**Comment by vsch** [comment]
@smartsal, you are welcome.

**Comment by uaibo** [comment]
One more thing, because I'm pulling my hair out. 

_I'm in another project now_, using **Laravel v.5.2** and **Laravel Translation Manager v.2.1** 
I followed the installation that you suggested above, for Laravel 5.2.

When I go to /public/translations I get an Error 404 page so I can't access translations.

When I run **php artisan route:list** it appears the routes are registered though: https://i.gyazo.com/fb384a732bc130e58961888afeb04e01.png

but **\vendors\vsch\laravel-translation-manager\src\Controller\getIndex()** is not being used at all - if I put whatever - die('this method is used') - nothing happens and I still get 404 page.

Do you have any idea what could be going wrong?

**Comment by vsch** [comment]
@smartsal, is there another package modifying the route mapping? For example based on localization information.

Also, is the right path `/public/translations` or just `/translations`?

**Comment by uaibo** [comment]
Ahh, found it!
You hit the nail in the head once again. I was using **/public/{slug}** in my routes to get pages dynamically based on their slug, and that was obviously overriding/modifying it: https://i.gyazo.com/9a99ba723269b7b633959e47e6833e2d.png

I commented them out and now it's working: https://i.gyazo.com/640d2c4d6ba3668fba56e6652ce1bf79.png

I know that's a poor method to handle dynamic pages based on slug, but I have done it a few months ago when I was just starting with Laravel. Will have to improve on that. 

Thanks for pointing me in the right direction though. 
Have a great day bro!

**Comment by vsch** [comment]
@smartsal, I used to be a consultant and these types of solutions were often a necessity. Customer emergency fix now with a more robust solution later. Later, clients often refused to spend money on fixing something that in their understanding was already working.

There is the ideal practice of software development and then there is the ugly reality of how those that write the checks and approve work orders see it.
