### ISSUE TITLE
Need a event after publishing Translation files

### ISSUE THREAD

**Issue by approached** [vsch/laravel-translation-manager#87]
Hi@all

Need a event after publishing Translation files.

Can anybody develop this? I need this feature.

Now i use this:
 ```php
Event::listen('Illuminate\Routing\Events\RouteMatched', function (RouteMatched $routeMatched) {

            /** @var Request $request */
            $request = $routeMatched->request;

            if (
                strpos($request->getPathInfo(), '/translations/publish/') !== false &&
                $request->getMethod() === 'POST'
            ) {

                ...

            }
        });
```

Thanks

**Comment by vsch** [comment]
@approached, what information about the publish event do you need to know?

For example do you want to know the groups that were published and do you need any error information from the publish action?

What is the end result for which you use this event?

**Comment by approached** [comment]
Good question. It is very simply. Me doesn't need any information.

It is just a hook for pushing languages files with git to github.

**Comment by vsch** [comment]
@approached, I added an event `Vsch\TranslationManager\Events\TranslationsPublished` the event class has two attributes: 

* `groups`, string of the groups parameter, either `*` if all or group name
* `errors`, array of errors resulting from the publishing.

Event is generated when publish is invoked through the Web UI or export from the command line.

Will make a new release shortly.

**Comment by vsch** [comment]
@approached, version 2.4.12 with event support released.

**Comment by approached** [comment]
Thank you for your commit.
