### ISSUE TITLE
Import fails without feedback, file translations being deleted on publishing

### ISSUE THREAD

**Issue by gerardreches** [vsch/laravel-translation-manager#88]
My `laravel.log` file registers this error each time I use the **Import all** or **Import** from the webUI. I get no feedback in the webUI from that error, it just does nothing.

> [2017-05-24 18:19:49] staging.ERROR: ErrorException: file_exists(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/vhosts/mydomain.com/:/tmp/) in /var/www/vhosts/mydomain.com/d550.mydomain.com/vendor/vsch/laravel-translation-manager/src/Classes/PathTemplateResolver.php:328

So the existing translations in the files are not being imported, and when I publish the new translations the old ones are being deleted because they are not registered in the database.

**Comment by vsch** [comment]
@gerardreches, thank you for reporting this. I will add logic to eliminate test for the root directory `/` which is a bug since it always exists.

**Comment by vsch** [comment]
@gerardreches, new version released with a fix for this bug.

**Comment by gerardreches** [comment]
Thanks! I will test it again tomorrow :)

**Comment by gerardreches** [comment]
Now there is no error, but **Import all** is not importing any items! :(

**Comment by vsch** [comment]
@gerardreches, it is hard to figure out what is wrong without having any idea of the project configuration or the translation contents. If it is not proprietary can you zip the lang directory and e-mail it to me so I can test it. Also please send me the ltm config file. e-mail: vladimir at vladsch dot com.

**Comment by 0x0FA8** [comment]
Hi, error in file PathTemplateResolver.php
line 249:call $this->loadFileList('/', $path_parts, []);
$prefix == '/' in procedure loadFileList line 329 condition always TRUE

**Comment by vsch** [comment]
@SergeRPM, my bad I had the condition reversed. Fixed and released.

**Comment by gerardreches** [comment]
Solved in 2.4.22, thanks @vsch !
