### ISSUE TITLE
Why some translations starts with <<<'TEXT'  and ends with TEXT in the language file?

### ISSUE THREAD

**Issue by gerardreches** [vsch/laravel-translation-manager#89]
Some of my translations starts with `<<<'TEXT'`  and ends with `TEXT`, I didn't put that, it's being done by the package after publishing the translations from the webUI.

```
<?php

return [
    'Frequent-asked-questions'  => 'Preguntas Frecuentes',
    'transactions'              => [
        'applicable-legislation'    => [
            'content'   => <<<'TEXT'
<p>El Reglamento de la Organización y régimen del Notariado (Decreto de 2 junio de 1944) y sus posteriores modificaciones, en su artículo 144 y en los artículos 198 a 220, ambos inclusive respectivamente.</p>
TEXT
,
        ],
    ],
];
```

These translations works, but I would like to know what's that syntax and if it should be there.

**Comment by vsch** [comment]
@gerardreches, HERE_DOC format for strings is used when a translation contains multi-line text. i.e. an end of line.

**Comment by gerardreches** [comment]
Thanks for the explanation, I couldn't find anything about it on google.
