### ISSUE TITLE
Incompatibilities with mcamara/laravel-localization

### ISSUE THREAD

**Issue by gerardreches** [vsch/laravel-translation-manager#90]
I'm in Laravel 5.4, using this package with [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization), and I found some incompatibilities.

**mcamara/laravel-localization** uses some functionalities of the default Laravel Translator, like passing a `$locale` to the `trans()` function. In the default Laravel Translator, `$locale` is the third parameter in `trans()`, but in **laravel-translator-manager** Translator class, the method is overwritten with the following:

    /**
     * Get the translation for a given key.
     *
     * @param  string $id
     * @param  array  $parameters
     * @param  string $domain
     * @param  string $locale
     *
     * @return string
     */
    public function trans($id, array $parameters = array(), $domain = 'messages', $locale = null, $useDB = null)
    {
        return $this->get($id, $parameters, $locale, $useDB);
    }

Where `$domain` is in the place where `$locale` should be. Other packages trying to use this method will have an issue with locales. Furthermore, the `$domain` parameter is not doing anything, so it should be removed or, at least, moved to another position that doesn't override parameters order of default `trans()` method.

    /**
     * Get the translation for a given key.
     *
     * @param  string $id
     * @param  array  $parameters
     * @param  string $locale
     *
     * @return string
     */
    public function trans($id, array $parameters = array(), $locale = null, $useDB = null)
    {
        return $this->get($id, $parameters, $locale, $useDB);
    }

I'm not sure if `$domain` was there for some reason. I can make a pull request for that if you want.

----

There is another problem that has more code involved and I'm not sure about the proper way to fix it: 

The `get()` method in Translator.php has been overwritten as well, and it seems like it's breaking some of the default functionality. **mcamara/laravel-localization** offers a way for translating routes, and that feature is working with the default Translator, but not with the overwritten one.

I think that the problem is that the custom Translator misses this check when a `$locale` is not provided in the call:

        // Here we will get the locale that should be used for the language line. If one
        // was not passed, we will use the default locales which was given to us when
        // the translator was instantiated. Then, we can load the lines and return.
        $locales = $fallback ? $this->localeArray($locale)
                             : [$locale ?: $this->locale];

        foreach ($locales as $locale) {
            if (! is_null($line = $this->getLine(
                $namespace, $group, $locale, $item, $replace
            ))) {
                break;
            }
        }

**Comment by vsch** [comment]
@gerardreches, thank you for reporting this. I will fix this and release.

**Comment by vsch** [comment]
@gerardreches, fixed version released. Translator method parameters modified to match the Laravel API.

**Comment by gerardreches** [comment]
@vsch Great. What about the second part of the issue?

**Comment by vsch** [comment]
@gerardreches, that one should now work too. The LTM `get()` was missing `$fallback` argument. Added and passed to `parent::get()`

**Comment by gerardreches** [comment]
@vsch Whoops! It seems that there is an internal change on Laravel in `trans()` arguments between versions 5.3 and 5.4. [Look at this question for reference](https://github.com/mcamara/laravel-localization/issues/448#issuecomment-305768697)

So the parameters were correct in Laravel 5.3, but not in Laravel 5.4. Since you defined version `~2.4` exclusive for Laravel 5.4, the fix should not be a problem.

I will close this issue and open a new one for the second one, I have an idea about what can happen.
