### ISSUE TITLE
Cookies generating wrong locales

### ISSUE THREAD

**Issue by gerardreches** [vsch/laravel-translation-manager#91]
### Using Laravel 5.4

This is the original **Translator.php**:

_vendor\laravel\framework\src\Illuminate\Translation\Translator.php_

    public function get($key, array $replace = [], $locale = null, $fallback = true)
    {
        list($namespace, $group, $item) = $this->parseKey($key);

        $locales = $fallback ? $this->localeArray($locale)
                             : [$locale ?: $this->locale];

        foreach ($locales as $locale) {                               // LINE 122
            if (! is_null($line = $this->getLine(
                $namespace, $group, $locale, $item, $replace
            ))) {
                break;
            }
        }

        if (isset($line)) {
            return $line;
        }

        return $key;
    }

When debugging with the package disabled, I got the correct locales for my app using a breakpoint in `line 122`:

![imagen](https://cloud.githubusercontent.com/assets/7549815/26733394/fcddd23a-47ba-11e7-9c62-bd50c45c5318.png)

But when I activate the package it sets my app locale to the value of the cookie it generates:

![imagen](https://cloud.githubusercontent.com/assets/7549815/26733482/3eb085d6-47bb-11e7-800e-5fc3b1282779.png)

With this incorrect value, it takes the fallback locale, so the translations are not working properly. I had to add

    'use_cookies' => false,

in the package config file in order to avoid that error, but since this config option is not there by default, I think that adding this isn't the default package approach.

**Comment by vsch** [comment]
@gerardreches, I will add it to the default config and install documentation.
