### ISSUE TITLE
Translation files can not be loaded 

### ISSUE THREAD

**Issue by approached** [vsch/laravel-translation-manager#92]
Hello,

after i updated to version **2.4.20**, the translation files can not be loaded.

I found the error

https://github.com/vsch/laravel-translation-manager/commit/bdbdb1356030d1bc34d870b9d212d053f449a06e Line 328

I have no idea, how i can fix it. Can anybody fix it?

Thanks

**Comment by vsch** [comment]
@approached, thank you for the report. My bad, it is wrong logic. I'll fix it and make a release.

**Comment by gerardreches** [comment]
@vsch Using version **2.4.22** on my staging environment, where the project shouldn't try to read parent files and folders:

> [2017-06-27 12:14:07] staging.ERROR: ErrorException: file_exists(): open_basedir restriction in effect. File(/var) is not within the allowed path(s): (/var/www/vhosts/myvps/:/tmp/) in /var/www/vhosts/myvps/myproject/vendor/vsch/laravel-translation-manager/src/Classes/PathTemplateResolver.php:328
