### ISSUE TITLE
laravel 5.4 default_connection

### ISSUE THREAD

**Issue by ghost** [vsch/laravel-translation-manager#93]
Здравствуйте.
У меня проблема с default_connection lara 5.4 в 5.3 работало.
Для translations у меня отдельная база laravel_translations, 
соответственно у меня есть connection mysql_translations,
лара ругается что нет db ltm_translations.
Возможно я неправильно настриаваю translation-manager...
Я для себя решил поправкой в вашем коде, в моделях Translation и UserLocales:
```
    /**
     * The database connection used by the model.
     *
     * @var string
     */
    protected $connection;

    /**
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->connection = config('laravel-translation-manager.default_connection');
    }
```
Сейчас все в норме
Как то так...
Спасибо.

**Comment by ghost** [comment]
В общем, пока так, для меня пока не критично.
Всего хорошего!

**Comment by vsch** [comment]
@alehtrem, I applied the changes and made a new release. I don't see why this would be needed because the `Manager` sets the connection name on translations but I added the code since it does not change the code.

**Comment by ghost** [comment]
Спасибо! Мой проект в стадии dev, я использую разные базы в одном проекте, в версии laravel 5.3, таких проблем не было, но потом начались, я не отследил с какой версии, если база для модели по умолчанию, то не надо явно указывать соеденение в модели, если другая база, то да, надо явно указывать другое соеденение. Наверное такую логику мало кто использует и отсюда нет проблем в этом плане... Надо как то разобраться... будет время...
