### ISSUE TITLE
Laravel Gate

### ISSUE THREAD

**Issue by ghost** [vsch/laravel-translation-manager#94]
Приветвую Владимир.
Вопрос к вам.
В Debugbar у меня включен Gate
и идет много обращений к Gate -> ltm-bypass-lottery, т.е. при каждом trans() в коде.
Это нормально? влияет ли это на скорость? т.е. не обращать внимания?
Спасибо!

![screenshot from 2017-07-28 14-38-47](https://user-images.githubusercontent.com/30339292/28717541-876b38b2-73a2-11e7-95a3-19ea479eafbc.png)

![screenshot from 2017-07-28 14-05-27](https://user-images.githubusercontent.com/30339292/28717571-a1e67a62-73a2-11e7-95dd-f7ebeaf9577d.png)

![screenshot from 2017-07-28 14-03-26](https://user-images.githubusercontent.com/30339292/28717297-75cda1f4-73a1-11e7-8e8d-d3aeae405b58.png)

**Comment by vsch** [comment]
@alehtrem, если не возражаете я отвечу на английском потому что печатаю минимум в 10 раз быстрее чем на русском. В защиту, последний мой класс в СССР был 4й в, 1972 году. 😊 

The ability is accessed because there are some undefined translations and it is checking if the missing keys should be tracked for this user based on a random selection or for every key. You are right, depending on the implementation of this "ability" it may impact performance, especially if there are a lot of missing translations on a page.

I changed the code in Translator to cache the value on first access and re-use it. I will make a release shortly.

**Comment by ghost** [comment]
@vsch  Спасибо за ответ! Конечно я не против :) . Я вас понимаю. А я в 1972 году в 1 класс пошёл :) , забавно. Сейчас живу в Бельгии, недавно, но вот с английским и нидерландским ну пока никак, тяжеловато, на русском мне пока легче.
Спасибо вам за этот классный пакет! Буду ждать релиза. Всего хорошего! Ааа уже!!!

**Comment by ghost** [comment]
Нет не изменилось.
P.S. Простите, не дописал, может это важно, это происходит не в самом
интерфейсе переводчика, там в норме, а на любой другой странице сайта. 
Я дебагером проверил, дергает тут:
```
protected function notifyUsingKey($key, $locale = null)
    {
        if (!$this->suspendUsageLogging) {
            list($namespace, $group, $item) = $this->parseKey($key);
            if ($this->manager && $group && $item && !$this->manager->excludedPageEditGroup($group)) {
                $this->manager->usingKey($namespace, $group, $item, $locale, !\Gate::allows(Manager::ABILITY_BYPASS_LOTTERY));
            }
        }
    }
```
Тут подставляю ваше решение, тогда в норме, не уверен правильно ли, т.к. не знаю логики...
```
protected function notifyUsingKey($key, $locale = null)
    {
        if (!$this->suspendUsageLogging) {
            list($namespace, $group, $item) = $this->parseKey($key);
            if ($this->manager && $group && $item && !$this->manager->excludedPageEditGroup($group)) {
                $this->manager->usingKey($namespace, $group, $item, $locale, $this->isUseLottery());
            }
        }
    }
```

**Comment by vsch** [comment]
@alehtrem, yes this would be the cause. I relied on PhpStorm IDE to refactor all occurrences and did not verify that all were change. I applied the fix to the other two locations and made a new release.

Thank your for double checking it.

BTW, мы эмигрировали когда мне было 9, а в 12 лет мы уже приземлились в Канаде. Для меня английский язык как родной. Мой младший брат уже говорит на русском с трудом. Все зависит от возраста. Чем старше тем труднее освоить новый язык. Чем младше тем легче забыть если его не употреблять.

**Comment by ghost** [comment]
Спасибо! Сейчас все в порядке. 
BTW, пишу вот вам на французской клаве, еще машинально помню буквы. В те далекие 70 годы, много уехало людей, моих соседей, знакомых, я сам из Беларуси. Вот и я уже 6 год тут в Бельгии, во Фландрии, здесь фламский тот же нидердандский язык но только мягче и красивее. Да вы правы с возрастом наверное тежелее осваивать новый язык, но тут без знания языка проблеммы, так что стараюсь... Прикольно тут тоже слышать русскоговорящих людей которые тут с самого детства, мыслят на нидерланском но мысли эти выражают на русском языке, смешно....
Спасибо и всего вам хорошего!
