### ISSUE TITLE
laravel 5.5 support?

### ISSUE THREAD

**Issue by Bonobomagno** [vsch/laravel-translation-manager#96]
any plan?
you used 5.5 strict so no way to install on laravel 5.5 ( i mean, using * instead of 2.4.* i got a laravel 5.3 version. there is a share method instead of singleton)

at least remove the <5.5 for now
So who use 5.5-dev can test it and maybe fix it before 5.5 will be released.

**Comment by vsch** [comment]
@Bonobomagno, I removed the unnecessary <5.5 and made a release.

**Comment by Bonobomagno** [comment]
thanks,
i'm reporting the new error log. Some change will be asked for support 5.5
```>Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Vsch\TranslationManager\Translator::__cons
  truct() must be an instance of Illuminate\Translation\LoaderInterface, inst
  ance of Illuminate\Translation\FileLoader given, called in /home/vagrant/Co
  de/mydir/vendor/vsch/laravel-translation-manager/src/TranslationServic
  eProvider.php on line 44
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1```

**Comment by ghost** [comment]
@vsch
@Bonobomagno 

https://laravel.com/docs/5.5/upgrade
**Translation:**

The **LoaderInterface**
The Illuminate\Translation\LoaderInterface interface has been **moved to**  Illuminate\Contracts\Translation\Loader.

And add auto-discovered this vendor in composer.json:
**Examples:**
https://laracasts.com/series/whats-new-in-laravel-5-5/episodes/5
```
"extra": {
        "laravel": {
            "providers": [
                "Vsch\\TranslationManager\\TranslationServiceProvider",
                "Vsch\\TranslationManager\\ManagerServiceProvider"
            ]
        }
    },
```

**Comment by Bonobomagno** [comment]
laravel 5.5 is out :)

**Comment by vsch** [comment]
@Bonobomagno, thank you for the heads up. I will update LTM for 5.5 and make a release.

**Comment by RamonSmit** [comment]
Cant wait :)

**Comment by vsch** [comment]
Version 2.5.0 updated for Laravel 5.5 compatibility based on the upgrade docs.

**Comment by Bonobomagno** [comment]
Tested: is working.
Just a thing, what about autodiscovery? did you think will be possible?

**Comment by vsch** [comment]
@Bonobomagno, auto-discovery for Laravel versions? Tried that with 4 and 5 and it created a mess in the code. Laravel tends to change (called improvement in Laravel terms) in backward breaking ways. It is great for those that like to be on the bleeding edge and work with it full time, so keeping up with the changes is part of a day's work.

However, I have not done active development in Laravel in over a year and all the breaking changes are a PITA to follow.

**Comment by Bonobomagno** [comment]
Is not so usefull, but if you use translation manager only on locale, then
commit the update, can be nice to have.

Il 06 set 2017 18:37, "Vladimir Schneider" <notifications@github.com> ha
scritto:

@Bonobomagno <https://github.com/bonobomagno>, auto-discovery for Laravel
versions? Tried that with 4 and 5 and it created a mess in the code.
Laravel tends to change (called improvement in Laravel terms) in backward
breaking ways. It is great for those that like to be on the bleeding edge
and work with it full time, so keeping up with the changes is part of a
day's work.

However, I have not done active development in Laravel in over a year and
all the breaking changes are a PITA to follow.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vsch/laravel-translation-manager/issues/96#issuecomment-327541786>,
or mute the thread

**Comment by Konafets** [comment]
The problem I see with auto discovery here is that you need to remove the old `Illuminate\Translation\TranslationServiceProvider::class`.
