### ISSUE TITLE
indatabase_publish not working as intended

### ISSUE THREAD

**Issue by isbkch** [vsch/laravel-translation-manager#98]
Even after changing indatabase_publish to 1 or 2, the interface still reads from the files after publishing. The DB values don't change as well.

Anything I should be looking for ?

**Comment by vsch** [comment]
@isbkch, in database publish caches, via \Cache:: facade, changed translations with a key  of `persistent_prefix` with  "translations" appended to it.

So you need to have the persistent prefix defined and \Cache:: facade for some type of cache implementation.

Are there any exceptions when you publish?

**Comment by isbkch** [comment]
- I have the persistent_prefix defined as "translator_" 
- I get the translation the same way I used to get it from files, using : trans('tour/home.page-title')
- No exceptions when I publish
- I use Redis as Cache
- When I monitor Redis, there are no entries in the cache with the prefix translator

Anything else I should check ?

**Comment by vsch** [comment]
@isbkch, it is a bug for translation files in sub-directories. The group in the cache is wrong. It only takes the first part of the key as the group. A left-over from a time when sub-directories weren't supported.

I have the fix and will release a new version. Are you running Laravel 5.5 or 5.4? I will have to update both versions with the fix.

**Comment by isbkch** [comment]
@vsch thank you for the quick reply. I'm running at the moment Laravel 5.3

**Comment by vsch** [comment]
@isbkch, I will add the fix to 5.3 too.

**Comment by vsch** [comment]
@isbkch, version 2.3.8 has the fix for laravel 5.3. Composer update should do the trick.
