### ISSUE TITLE
Regex doesnt clear

### ISSUE THREAD

**Issue by Bonobomagno** [vsch/laravel-translation-manager#99]
It seem that regex doesnt empty if you delete the textbox. If you change traslation group, the regex setup himself on last typed text. But empy text is not valid, so after first time that you write on the regex, there is no way to empty it!

**Comment by Bonobomagno** [comment]
Of course if i use /* all are shown, but still is not so nice too use

**Comment by vsch** [comment]
@Bonobomagno, what do you mean by "delete the textbox" and are you referring to the "key regex"?

**Comment by Bonobomagno** [comment]
if i press on id=show-matching-clear and after i change the group, the matching will not be clear. Instead will have the last pre-clear text, every time!

**Comment by vsch** [comment]
I cannot duplicate the behavior. 

1. Select a group
2. Set the regex text.
3. Change group (the text remains by design)
4. Press the x to clear the regex (regex now empty)
5. Change group (regex is still empty)

The regex and filters (new, used, unused, etc) are sent to the server every time it changes to it is reloaded on page refresh using JSON. The URL used is controller url @getTransFilters.

On the server it is persisted in a cookie `trans-filters`

There must be some errors that prevent it from being cleared. Are you getting any errors in the browser console?

**Comment by Bonobomagno** [comment]
No errors,
On point 4, the trans-filters cookie doesnt change. So i need to manually delete it or empty it.
Any suggest for test it?

**Comment by vsch** [comment]
Config file has an option for persistent prefix and the cookie named with `trans-filters` appended to that prefix is set. Is your browser not allowing cookies to be set for that page?

You can just delete the cookie and it will reset the regex. Without the cookie the regex won't be preserved across page refreshes.

**Comment by Bonobomagno** [comment]
yeah i know, the cookie is fine becouse the filter is working. The only problem is that the cookie doesnt empty if i press X, as it should be.
What happened on press x? i will try to inspect. what function is called?

**Comment by vsch** [comment]
The function is `updateMatching` in [translations_page.js](https://github.com/vsch/laravel-translation-manager/blob/master/public/js/translations_page.js#L171-L254) file.

**Comment by Bonobomagno** [comment]
`    $('#show-matching-clear').on('click', function () {
        if (matchingText.length) {
            matchingText[0].value = '';
            matchingText.focus();
            updateMatching();
        }
    });
`
This dont run on inspect. i dunno why.

edit.
It delete che filter content, but doesnt emtpy the cookie. so on page update che old regex is still here.

**Comment by vsch** [comment]
No errors on page loading?

**Comment by Bonobomagno** [comment]
nop. I tracked down a bit. translation_page is working, but the get request seem ignored. Maybe becouse the send regex variable is empty. I'm using php7.1.7 So i now need to check the controller. where it is?

**Comment by vsch** [comment]
[Controller@getTransFilters](https://github.com/vsch/laravel-translation-manager/blob/master/src/Controller.php#L931-L956)

**Comment by Bonobomagno** [comment]
Ok, i got the error.
When you press on X, it send an null regex value. But there is a check on the controller:

`if ($regex !== null) {
            $this->transFilters['regex'] = $regex;
        }`
If it is null, and it is null, transfilter doenst get reset. Instead it use the old value. (you can just dd it to see that)
Maybe something changed on php7.1 , i dunno but i think that we need a fix here.
I will made a PR now if you want.

**Comment by Bonobomagno** [comment]
ah ok. is fine for me
